rgb: true
palette: dmc
dither: false
greyscale: false
quantize:
  enabled: false
  n: 7
csv: ""
width: 150
log_level: 1
# metric = true: use metric units
# metric = false: use imperial units
metric: false
#excludes: []
# Information about modes
dmc:
  pixel_size_mm: 1.8
  fabric:
    enabled: true
    name: Aida 14ct
    color: black
anchor:
  pixel_size_mm: 1.8
  fabric:
    enabled: true
    name: Aida 14ct
    color: black
lego:
  pixel_size_mm: 8
